local a = {
  "vscode.java.checkProjectSettings",
  "vscode.java.isOnClasspath",
  "java.project.list",
  "vscode.java.fetchUsageData",
  "java.navigate.openTypeHierarchy",
  "sts.project.gav",
  "sts.java.hierarchy.supertypes",
  "java.edit.handlePasteEvent",
  "qute/template/projects",
  "sts.java.hierarchy.subtypes",
  "java.edit.stringFormatting",
  "vscode.java.resolveMainClass",
  "vscode.java.test.navigateToTestOrTarget",
  "vscode.java.buildWorkspace",
  "qute/template/project",
  "vscode.java.resolveJavaExecutable",
  "sts.java.type",
  "java.project.refreshLib",
  "java.project.checkImportStatus",
  "java.project.refreshDiagnostics",
  "qute/template/generateMissingJavaMember",
  "vscode.java.test.findTestPackagesAndTypes",
  "vscode.java.resolveInlineVariables",
  "java.project.listSourcePaths",
  "sts.java.search.packages",
  "java.project.resolveText",
  "qute/java/diagnostics",
  "java.project.getClasspaths",
  "java.project.updateSourceAttachment",
  "vscode.java.resolveClasspath",
  "vscode.java.resolveBuildFiles",
  "java.decompile",
  "vscode.java.test.resolvePath",
  "vscode.java.resolveSourceUri",
  "vscode.java.test.findTestLocation",
  "vscode.java.test.findDirectTestChildrenForClass",
  "vscode.java.fetchPlatformSettings",
  "java.project.resolveSourceAttachment",
  "sts.java.removeClasspathListener",
  "java.project.addToSourcePath",
  "java.completion.onDidSelect",
  "vscode.java.startDebugSession",
  "qute/java/documentLink",
  "java.project.import",
  "java.project.changeImportedProjects",
  "vscode.java.validateLaunchConfig",
  "java.project.resolveStackTraceLocation",
  "qute/template/projectDataModel",
  "vscode.java.test.junit.argument",
  "vscode.java.test.generateTests",
  "vscode.jav a.resolveMainMethod",
  "java.project.getSettings",
  "vscode.java.test.jacoco.getCoverageDetail",
  "java.project.resolveWorkspaceSy mbol",
  "sts.java.addClasspathListener",
  "vscode.java.test.findTestTypesAndMethods",
  "java.project.upgradeGradle",
  "sts.java.cod e.completions",
  "qute/java/codeLens",
  "java.project.createModuleInfo",
  "vscode.java.test.get.testpath",
  "java.resolvePath",
  "st s.java.javadoc",
  "vscode.java.resolveElementAtSelection",
  "java.vm.getAllInstalls",
  "java.edit.organizeImports",
  "qute/template /userTags",
  "java.project.generateJar",
  "qute/template/javaTypes",
  "java.project.removeFromSourcePath",
  "sts.java.javadocHoverL ink",
  "java.project.updateSettings",
  "java.project.getAll",
  "java.reloadBundles",
  "java.project.isTestFile",
  "sts.java.search.t ypes",
  "vscode.java.resolveClassFilters",
  "java.getPackageData",
  "qute/template/javadoc",
  "java.navigate.resolveTypeHierarchy",
  "java.edit.smartSemicolonDetection",
  "qute/template/javaDefinition",
  "vscode.java.test.findJavaProjects",
  "java.project.update ClassPaths",
  "java.project.getMainClasses",
  "qute/template/resolvedJavaType",
  "vscode.java.updateDebugSettings",
  "sts.java.loca tion",
  "java.protobuf.generateSources",
  "java.project.updateJdk",
  "vscode.java.inferLaunchCommandLength",
}
